
export const Translate = {

    EN: {
        selectLang: "Language",
        selectCurensy: "Currensy",
        login: "Log in",
        signin: "Sign in",    
        login2: "Log in",   
        signin2: "Sign in",
        home: "HOME",
        women: "WOMEN",    
        men: "MEN",
        other: "OTHER",
        cart: "Cart",     
        products: "Featured Products",    
        filter: "Filter:",
        all: "All",
        new: "New:",      
        sale: "Sale:",     
        cal: "Free shipping on orders over $100",    
        callin2: "call us! to free- 409-8888-0099",
        soch1: "FACEBOOK",
        socp1: "Members",    
        socp2: "Facebook Social plugin",    
        soch2: "FROM TWITTER",
        soch2p1: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
        soch2p2: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        soch3: "INFORMATION",
        info: "Shipping and returns.",  
        info2: "Online store guarantees.",
        info3: "Privacy policy.", 
        info4: "Public offer agreement.",
        info5: "Certificates.", 
        abousUs: "About Us",
        returns: "Delivery & Returns",
        terms: "Terms & Conditions",
        contactUs: "Contact Us",
        },

    RU: {
        selectLang: "Язык:",
        selectCurensy: "Валюта",
        login: "Войти",
        signin: "Регистрация",    
        login2: "Войти",   
        signin2: "Регистрация",
        home: "ГЛАВНАЯ",
        women: "ЖЕНСКИЕ",    
        men: "МУЖСКИЕ",
        other: "ОСТАЛЬНЫЕ",
        cart: "Корзина",     
        products: "Рекомендуемые Продукты",    
        filter: "Фильтр",
        all: "Все",
        new: "Новые",      
        sale: "Распродажа",     
        cal: "Бесплатная доставка при заказе от $100",    
        callin2: "Позвоните нам! Бесплатно - 409-8888-0099",
        soch1: "FACEBOOK",
        socp1: "Члены",    
        socp2: "Социальный плагин Facebook",    
        soch2: "С ТВИТЕРА",
        soch2p1: "Lorem Ipsum — это просто текст-пустышка полиграфической и наборной индустрии. Lorem Ipsum является отраслевым стандартом",
        soch2p2: "Интернет — это просто текст-пустышка полиграфической и наборной индустрии. ",
        soch3: "ИНФОРМАЦИЯ",
        info: "Доставка и возврат",  
        info2: "Гарантии интернет магазина",
        info3: "Политика конфиденциальности", 
        info4: "Договор публичной оферты",
        info5: "Сертификаты", 
        abousUs: "О нас",
        returns: "Доставка и возврат",
        terms: "Условия",
        contactUs: "Связаться с нами",
    },

    UA: {
        selectLang: "Мова:",
        selectCurensy: "Валюта",
        login: "Увійти",
        signin: "Реєструватися",    
        login2: "Увійти",   
        signin2: "Реєструватися",
        home: "ГОЛОВНА",
        women: "ЖІНОЧІ",    
        men: "ЧОЛОВІЧІ",
        other: "ІНШІ",
        cart: "Корзина",     
        products: "Рекомендовані Товари",    
        filter: "Фільтр",
        all: "Всі",
        new: "Нові",      
        sale: "Продаж",     
        cal: "Безкоштовна доставка при замовленні понад $100",    
        callin2: "Зателефонуйте нам! безкоштовно - 409-8888-0099",
        soch1: "FACEBOOK",
        socp1: "Члени",    
        socp2: "Соціальний плагін Facebook",    
        soch2: "З ТВІТЕРУ",
        soch2p1: "Lorem Ipsum — це просто фіктивний текст поліграфічної та набірної промисловості. Lorem Ipsum був стандартом галузі",
        soch2p2: "Інтернет — це просто фіктивний текст поліграфічної та набірної промисловості.",
        soch3: "ІНФОРМАЦІЯ",
        info: "Доставка та повернення",  
        info2: "Гарантії інтернет магазину",
        info3: "Політика конфіденційності", 
        info4: "Договір публічної оферти",
        info5: "Сертифікати", 
        abousUs: "Про нас",
        returns: "Доставка та повернення",
        terms: "Положення та умови",
        contactUs: "Зв'яжіться з нами",
    },
}
